# Generated by Django 3.0.4 on 2021-07-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=255, verbose_name='Option')),
                ('speed', models.IntegerField(max_length=255, verbose_name='Speed')),
                ('first_fee', models.IntegerField(max_length=255, verbose_name='FirstFee')),
                ('over_fee', models.IntegerField(max_length=255, verbose_name='OverFee')),
            ],
        ),
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField(verbose_name='ProviderID')),
                ('provider_name', models.CharField(max_length=255, verbose_name='ProviderName')),
                ('spot_id', models.IntegerField(verbose_name='SpotID')),
                ('spot_name', models.CharField(max_length=255, verbose_name='SpotName')),
                ('spot_coordinateX', models.FloatField(verbose_name='SpotCoordinateX')),
                ('spot_coordinateY', models.FloatField(verbose_name='SpotCoordinateY')),
                ('spot_address', models.CharField(max_length=255, verbose_name='SpotAdress')),
            ],
        ),
        migrations.AddConstraint(
            model_name='spots',
            constraint=models.UniqueConstraint(fields=('provider_id', 'spot_id'), name='spots_unique'),
        ),
    ]
